### ISSUE TITLE
BicepBuild@0 Devops Task issue

### ISSUE THREAD

**Issue by AMcDonald7** [piraces/azure-devops-bicep-task#2]
Hello,
I am having an issue with the above task in Azure DevOps pipeline

Step look like this:
#Build all .bicep files into .json counterparts

steps:
  - task: BicepBuild@0
    inputs:
      sourceDirectory: '$(System.DefaultWorkingDirectory)/Infrastructure/Azure-Bicep-Deploy/BicepFiles/*.bicep'

The error from the pipeline is this:
![image](https://user-images.githubusercontent.com/75473052/110100317-2b4f8780-7d9a-11eb-9024-165bd4a0129a.png)

The document says it is possible to build multiple files. So I am a bit stuck as what to do

Any help appreciated.

Andrew

**Comment by piraces** [comment]
Hello @AMcDonald7 , 

Thanks for the report, I will review this behaviour ASAP. With the release 0.3.1 of bicep, many things have changed, so I will review the breaking ones and add support for the new options.

**Comment by AMcDonald7** [comment]
Thanks for the update.

**Comment by piraces** [comment]
This should be fixed by now. A new release has been published (v0.1.3), that fixes this issue.
Please make sure your organization has the latest version and your pipeline is using that latest version.

You can see it running as an example here: https://dev.azure.com/raulejea/Bicep%20Tasks/_build?definitionId=19
