### ISSUE TITLE
Version 0.3.7 does not find *.bicep files

### ISSUE THREAD

**Issue by EinmalIM** [piraces/azure-devops-bicep-task#21]
Version 0.3.7 of BicepBuild does not find any *.bicep files in "multiple" mode.
The same yaml with version 0.3.4 is working.
Is that a know issue? Any workaround (except using 0.3.4 explicitly)?

This happens on Windows based agents

**Comment by piraces** [comment]
Hi @EinmalIM I will investigate this ASAP and try to solve it. Thanks for reporting it 👍

**Comment by piraces** [comment]
Hi again @EinmalIM . I think I have successfully reproduced the bug in a Windows based agent, and the problem is with the [`glob`](https://www.npmjs.com/package/glob) dependency. It has some open issues that have not been solved and I have downgraded the version of `glob` to use the previous one (7.x).

I have tested it in several ways and now it is working as expected.

A new v0.3.8 of the extension is already published and rolling out with the fix.

Nevertheless, if you keep experiencing the same issue please do not hesitate to re-open this issue or comment here 👍

**Comment by EinmalIM** [comment]
Thank you very much for the quick fix - 0.3.8 is working for us again.
