### ISSUE TITLE
bicep build issue

### ISSUE THREAD

**Issue by pursca** [piraces/azure-devops-bicep-task#8]
when I used the predefined variable as Output directory for .json generated by Bicep: $(build.artifactstagingdirectory) and Output filename for the .json generated file, but it looks like the  $(build.artifactstagingdirectory) is ignore from the following logging of the execution command - so I could not locate where the rgdeploy.json is.

C:\hostedtoolcache\windows\bicep.exe\0.3.255\x64\bicep.exe build D:\a\1\s\SPI\SPIFuncApp.ResourceGroup\azuredeploy.bicep --outfile rgdeploy.json

**Comment by piraces** [comment]
Hello @pursca,

If I understood it, your $(Build.ArtifactStagingDirectory) is your desired `outdir` directory and you specified it as the output directory and `rgdeploy.json` as `outfile`.

Currently specifying a `outdir` and an `outfile` at the same time is not supported by the Bicep CLI. It will be better if the pipeline task indicates this. I will work on it.

Nevertheless, your file should be in the `D:\a\1\s\SPI\SPIFuncApp.ResourceGroup\rgdeploy.json` as it is ignoring the `outdir`.
Sorry for the inconveniences.

Please let me know if the location is the correct as I described.

**Comment by piraces** [comment]
There is a possibility of specifying an output directory and output filename if you put it together in the `outfile` parameter.

For example if you put in outputFile: `$(Build.ArtifactStagingDirectory)\rgdeploy.json`

**Comment by piraces** [comment]
Hi @pursca ,

I have updated the tasks in order to avoid selecting exclusive options regarding output options when using the classic Pipeline editor with a dropdown:
![image](https://user-images.githubusercontent.com/11027628/118361016-c5496280-b589-11eb-9368-35224cb4d10e.png)

I have also modified the README [explaining the output options preference and that they are mutually exclusive](https://github.com/piraces/azure-devops-bicep-task#important-notes).

I hope this solves the original issue you specified.

Nevertheless, if you find the same problem or another one, feel free to re-open this bug or create a new one.
